# Use the official Python base image with Python 3.9.6
FROM python:3.9.6-slim-buster

# Update package lists and install required system packages
RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get clean
    
# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the project dependenciesd
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project files to the container
COPY . .

# Expose the port on which the FastAPI server will run (change if needed)
EXPOSE 8000

# Set the environment variables
ENV SECRET=2ea7e571df496b58d0cd8cc4c0a329a8 \
    ALGORITHM=HS256 \
    MONGODB_USER=GenericUser \
    MONGODB_CLUSTER_NAME=atlascluster\
    PROJECT_NAME=CarSpaceReservations

# Start the FastAPI server with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]